---
- hosts: '{{ host_name }}' 
  remote_user: '{{ remote_username }}'
  become: yes
  become_method: sudo

  tasks:
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
     name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
     state: present
     update_cache: yes

  - name: Install pip
    apt: name=python-pip state=present
              
  - name: install docker-py
    pip: name=docker-py 

  - name: log into docker hub registry
    docker_login:
     email: "arkaghosh.nb@gmail.com"
     username: "arghosh"
     password: "February2019!"

  - name: ensure a container is running
    docker_container:
     name: onlinelibrary_container
     state: started
     image: "arghosh/onlinelibrary:latest"
     pull: true
     ports:
     - "5000:5000"
